# Site settings
title: CommonDoc

description: >
  A CLOS framework for representing and converting documents.
baseurl: ""

# Build settings
markdown: kramdown

# Variables
links:
  repo: https://github.com/CommonDoc/common-doc
  docs: /docs/overview.html
